### ISSUE TITLE
Use of File.deleteOnExit leaks memory

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/metro-mimepull#13]
The method MemoryData.createNext calls File.deleteOnExit. Unfortunately, this permanently adds an entry to a list of files. In our long running server application, the end result is a significant memory leak.
In our case, we don't have much use for this call to deleteOnExit anyway, as our system already cleans up all temporary files when the server stops. So if there is no better way, I would request a simple system property to disable this call.
#### Affected Versions
[1.9.4]

**Comment by iprem** [comment]
Any ETA on when the issue will be fixed?
