### ISSUE TITLE
Release 1.9.8

### ISSUE THREAD

**Issue by foygl** [eclipse-ee4j/metro-mimepull#38]
Out of curiosity what happened to release 1.9.8? It's not in Maven central but there are some libraries out there that have a dependency on it...

**Comment by Tomas-Kraus** [comment]
1.9.8 was Oracle release. I have no idea why it's not in central.
I released 1.9.11 yesterday and we are almost done with this Jakarta EE release so releasing old artifact does not make sense to me now.
You can use 1.9.10 which was released in September 2018. It was done with full Java EE stack (including Metro, GlassFish, ...).

**Comment by eazran** [comment]
so... looks like our missing 1.9.8 version is a transitive dependency of "spring-boot-starter-web-services"

That missing version is breaking spring-boot!

[DEBUG] Writing resolution tracking file .m2/repository/org/springframework/spring-oxm/5.1.4.RELEASE/_maven.repositories
[DEBUG]    org.springframework.boot:spring-boot-starter-web-services:jar:2.1.2.RELEASE:compile
.......
[DEBUG]       com.sun.xml.messaging.saaj:saaj-impl:jar:1.5.0:compile
[DEBUG]          javax.xml.soap:javax.xml.soap-api:jar:1.4.0:compile
[DEBUG]          org.jvnet.mimepull:mimepull:jar:1.9.8:compile

Sounds like a serious bug, no?

**Comment by lukasj** [comment]
should be in central in few hours
